### ISSUE TITLE
Question about `do_eval`

### ISSUE THREAD

**Issue by beishangeyu** [zhentingqi/rStar#15]
I noticed that in the `do_eval.py` file, the `eval_single_item_from_answer_sheets` function combines the solution traces from both the *Final Solutions* and *Rollout Solutions* files. Wouldn't this lead to duplication? I don’t quite understand the reasoning behind doing it this way.

**Comment by Thunderbeee** [comment]
Thanks for asking! From a general perspective it would not make too much difference in terms of runtime. However, if one want to delve into the details about what is going on within each rollout and their performance, `eval_output` is the place where you can get some insights which means solution traces from Final Solutions are not sufficient.

**Comment by beishangeyu** [comment]
Thanks a lot for your response and help!
