### ISSUE TITLE
Why can't I run the code? I followed all the steps in the readme.md exactly.

### ISSUE THREAD

**Issue by isxychao** [zhentingqi/rStar#9]
![image](https://github.com/user-attachments/assets/a9264979-e645-4bc7-be8b-11c26779ec5c)

**Comment by Kilimajaro** [comment]
I got the same trouble. Why?

**Comment by bvarjavand** [comment]
you need to 
1. set HF_TOKEN with an account that has access to the mistral model
2. In `common/arguments.py` on line 63, the post_process_args method needs a default args.mode value
```
if not hasattr(args, 'mode'):
    args.mode = 'run'
```
Adding this works for me, though I'm not sure if this is the "correct" solution

**Comment by JiahangXu** [comment]
Hi, sorry for the inconvenience. We have fixed the issue. Please pull the latest code from the repository and try again. Let us know if you encounter any other problems.

**Comment by JiahangXu** [comment]
Since there are no further discussions, I'll go ahead and close this issue for now. If you have any questions, feel free to reopen it anytime.
